apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverfilemanager-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: serverfilemanager
  template:
    metadata:
      labels:
        app: serverfilemanager
    spec:
      nodeSelector:
        rol: server
      containers:
      - name: serverfilemanager
        image: docker.io/bitboss629/serverfilemanager:v1
        volumeMounts:
        - name: server-storage
          mountPath: /FileManagerDir
      volumes:
      - name: server-storage
        hostPath:
          path: /home/ubuntu/compartido
          type: DirectoryOrCreate